# -*- coding: utf-8 -*-
"""Day 3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuZEWpk7cPYKEdcZCSDWZ8R3nQldwcby
"""

#List [mutable]
a = ['a','b','c']
print(len(a),a[1],type(a))
a[1]='k'
print(a)
a.remove('a')
print(a)

#tuple [Immutable]
A = (1,2,3)
type(A)

#set (no duplicates)
aa={1,2,3,4,5,5}
print(aa,len(aa))
aa.add(6)
aa.remove(5)
print(aa)

#dictionary
az={'man':'run','boy':'stand'}
print(az['man'])
az['key']='value'
print(az)
del az['boy']
print(az)

